### ISSUE TITLE
'use strict';

### ISSUE THREAD

**Issue by timmarinin** [noffle/docstrings#2]
Can `docstrings` ignore 'use strict' and use next available literal string?

``` js
function myExample() {
   'use strict'
   'This function is just an example'
}
```

**Comment by hackergrrl** [comment]
Oh wow, I didn't realize you could have function-level `use strict`. Do people actually do this (want strictness _only_ for a single function)?

**Comment by timmarinin** [comment]
@noffle it's [recommended by MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) to use function-level strict mode during code base transition from non-strict to strict.

**Comment by hackergrrl** [comment]
Welp, I'm sold. Sounds like a good addition. :)

**Comment by hackergrrl** [comment]
Done!
